### ISSUE TITLE
add basic follows_symlink support

### ISSUE THREAD

**Issue by redpig** [google/kati#30]
It'd be nice to be able to use symlinks for (sub)directories.

**Comment by shinh** [comment]
Though you have workarounded the issue by not using --use_find_emulator, two issues were found thanks to your report:

1. Kati thought symlink/file did not exist when symlink points a path outside the directories FindEmulator knew
2. Kati's findleaves.py didn't follow symlinks and it didn't fall back to the command execution.

1 was fixed by https://github.com/google/kati/commit/bd3bb23181d6bc220f64dc253ae76259611d6a61
2 was fixed by https://github.com/google/kati/commit/b7175615d59a91950d547c9c39a7c746c6f22c8b

As for 2, for your case (all top-level directories are symlinks) FindEmulator still just falls back to normal $(shell) command execution. This means you still don't have the performance improvement by FindEmulator (~20 secs for me), but you should be able to build your branch with --use_find_emulator after updating build/kati.

**Comment by shinh** [comment]
and

https://github.com/google/kati/commit/407d8d46b5ad545b7a6ef8ba930c6e08880e4b47

should make FindEmulator work nicely with your setup.

**Comment by redpig** [comment]
It's been performing well in a variety of test cases - thanks!
